on:
  push:
    branches:
      - main
  repository_dispatch:
    types:
      - update-github-releases

permissions:
  contents: write

jobs:
  update_github_releases:
    name: Update Github Release Index
    runs-on: ubuntu-latest
    concurrency:
      group: update-github-releases
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run index-github-releases
      - uses: stefanzweifel/git-auto-commit-action@3ea6ae190baf489ba007f7c92608f33ce20ef04a
